config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers do
      patch :best_answer, on: :member
    end
  end

  resources :badges, only: :index
  resources :files, only: :destroy
  resources :links, only: :destroy

  root to: "questions#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :best_answer, class_name: "Answer", optional: true

  has_one :badge, dependent: :destroy

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :badge, reject_if: :all_blank
  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :title, :body, presence: true

  def mark_as_best(answer)
    update(best_answer_id: answer.id)
  end

  def remove_mark_best
    update(best_answer_id: nil)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :load_question, only: [ :show, :edit, :update, :destroy ]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new(question: @question)
    @answer.links.new
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
  end

  def new
    @question = Question.new
    @question.build_badge
    @question.links.new # .build
  end

  def edit
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            "new_question",
            partial: "shared/redirect",
            locals: { url: question_path(@question) })
        end
        format.html { redirect_to @question }
      end
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            @question,
            partial: "questions/question",
            locals: { question: @question })
        end
        format.html { redirect_to @question }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if current_user&.author_of?(@question)
      @question.remove_mark_best if @question.best_answer.present?

      @question.destroy
      redirect_to questions_path, notice: "Your question was succesfully deleted"
    else
      redirect_to questions_path
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :title, 
      :body,
      files: [], 
      links_attributes: [ :name, :url ],
      badge_attributes: [ :title, :image ]
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: resource do |f|
  p
    = f.label :title
    = f.text_field :title
    - if resource.errors[:title].present?
      .error-title
        = resource.errors.full_messages_for(:title).join(", ")
  p
    = f.label :body, "Your question"
    = f.text_area :body
    - if resource.errors[:body].present?
      .error-body
        = resource.errors.full_messages_for(:body).join(", ")
  p 
    = f.label :files 
    = f.file_field :files, multiple: true, direct_upload: true
  p
    = f.fields_for :badge do |b|
      = b.label :title, "Title badge"
      = b.text_field :title
      = b.label :image 
      = b.file_field :image, direct_upload: true
  p 
  p Links:
  p 
  div data-controller="link"
    div data-link-target="newLink"

    template data-link-target="template"
      = f.fields_for :links, Link.new, child_index: "NEW_LINK_INDEX" do |l|
        = render "links/form", f: l

    p
        = button_tag "Add link", type: "button", data: { action: "link#add" }

  p= f.submit resource.persisted? ? 'Save' : 'Ask'

app/views/questions/_question.html.slim
turbo-frame id = dom_id(question)
  .question
    h1 = question.title
    p = question.body

    - if question.files.attached?
      ul
        - question.files.each do |file|
          li id = dom_id(file)
            = link_to file.filename.to_s, url_for(file)
            |  | 
            - if current_user&.author_of?(question)
              = link_to 'Delete file',
                file_path(file),
                data: { turbo_method: :delete, 
                        turbo_confirm: 'Are you sure?' }
    
    -if question.badge&.image&.attached?
     .badge
       = image_tag question.badge.image, width: 60, height: 45
       = question.badge.title
      
    p
      - if current_user&.author_of?(question)
        = link_to 'Edit question', 
                  edit_question_path(question), 
                  data: { turbo_frame: "question"}
        |  | 
        = link_to 'Delete question', 
                  question_path(question), 
                  data: { turbo_method: :delete, 
                          turbo_confirm: 'Are you sure?',
                          turbo_frame: '_top' }
  .links
    p Links:
    ul
      - @question.links.each do |link|
        li id=dom_id(link)
          - if link.gist?
            div data-controller="gist" data-gist="#{link.url}"
            |  
          - else
            = link_to link.name, link.url
            |  | 
          - if current_user&.author_of?(question)
            = link_to 'Delete link',
                       link_path(link),
                       data: { turbo_method: :delete, 
                               turbo_confirm: 'Are you sure?' }
        ul
        

app/views/questions/create.js.erb
$('.error-title, .error-body').html('');

<% if @question.errors.any? %>
  $('.error-title').html("<%= j @question.errors.full_messages_for(:title).join(', ') %>");
  $('.error-body').html("<%= j @question.errors.full_messages_for(:body).join(', ') %>");
<% else %>
  window.location = "<%= question_path(@question) %>";
<% end %>

app/views/questions/edit.html.slim
turbo-frame id = dom_id(@question)
  = render 'form', resource: @question

app/views/questions/index.html.slim
= link_to 'Ask question', new_question_path

- @questions.each do |question|
  p
    = link_to question.title, question_path(question)
    |  
    - if current_user&.author_of?(question)
        = link_to 'Delete question', 
                   question_path(question), 
                   data: { turbo_method: :delete, 
                   turbo_confirm: 'Are you sure?' }

app/views/questions/new.html.slim
turbo-frame#new_question
  = render 'form', resource: @question

app/views/questions/show.html.slim
= link_to 'All questions', questions_path

= render 'questions/question', question: @question

- if @best_answer.present?
  turbo-frame#best_answer
    = render 'answers/best_answer', answer: @best_answer, question: @question

h3 Other answers:
turbo-frame#answers
  = render 'answers/answers', answers: @other_answers, question: @question

- if user_signed_in?
  turbo-frame#new_answer
    = render 'answers/form', answer: @answer, question: @question, frame_id: "new_answer"
- else
   p Log in to write a answer

app/views/questions/update.js.erb
$('.error-title, .error-body').html('');

<% if @question.errors.any? %>
  $('.error-title').html("<%= j @question.errors.full_messages_for(:title).join(', ') %>");
  $('.error-body').html("<%= j @question.errors.full_messages_for(:body).join(', ') %>");
<% else %>
  $('.question').html("<%= j render @question %>");
<% end %>