config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers do
      patch :best_answer, on: :member
    end
  end

  resources :badges, only: :index
  resources :files, only: :destroy
  resources :links, only: :destroy

  root to: "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: "User"

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  def this_best
    question.best_answer_id == self.id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question, only: [ :create, :edit, :update, :destroy, :best_answer ]
  before_action :find_answer, only: [ :edit, :update, :destroy, :best_answer ]

  def create
    @answer = @question.answers.build(answer_params)
    @answer.author = current_user

    respond_to do |format|
      if @answer.save
        format.turbo_stream
        format.html { redirect_to @question }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(
            "new_answer",
            partial: "answers/form",
            locals: { answer: @answer, question: @question }),
            status: :unprocessable_entity
        end

        format.html do
          render "questions/show", status: :unprocessable_entity
        end
      end
    end
  end

  def update
    return unless @answer.author_id == current_user.id

    if @answer.update(answer_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            @answer,
            partial: "answers/answer",
            locals: { answer: @answer, question: @question }
          )
        end
        format.html { redirect_to @question }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    if @answer.this_best
      @question.remove_mark_best
    end

    if @answer.author_id == current_user.id
      @answer.destroy

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove(@answer),
            turbo_stream.update(
              "flash",
              partial: "shared/turbo_flash",
              locals: { notice: "Your answer was succesfully deleted" }) ]
        end

        format.html { redirect_to @question }
      end
    else
      redirect_to question_path(@question)
    end
  end

  def best_answer
    return unless current_user&.author_of?(@question)

    result = Answers::BestAnswerService.new(@question, @answer).call

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(
            "best_answer",
            partial: "answers/best_answer",
            locals: { answer: result[:best_answer], question: @question }),
          turbo_stream.update(
            "answers",
            partial: "answers/answers",
            locals: { answers: result[:other_answers], question: @question }),
          turbo_stream.update(
            "flash",
            partial: "shared/turbo_flash",
            locals: { notice: "This answer was chosen as the best" }) ]
      end
      format.html { redirect_to @question }
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [ :name, :url ])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
turbo-frame id = dom_id(answer) 
  p = answer.body

  .links
    p Links:
    ul
      - answer.links.each do |link|
        li id=dom_id(link)
          - if link.gist?
            div data-controller="gist" data-gist="#{link.url}"
            |
          - else
            = link_to link.name, link.url
            |  | 
          - if current_user&.author_of?(answer)
              = link_to 'Delete link',
                link_path(link),
                data: { turbo_method: :delete, 
                        turbo_confirm: 'Are you sure?' }
        ul

  - if answer.files.attached?
    ul
      - answer.files.each do |file|
        li id=dom_id(file)
          = link_to file.filename.to_s, url_for(file)
          |  | 
          - if current_user&.author_of?(answer)
            = link_to 'Delete file',
              file_path(file),
              data: { turbo_method: :delete, 
                      turbo_confirm: 'Are you sure?' }
  p
    - if answer.persisted? && current_user&.id == answer.author_id
      = link_to 'Delete answer',
                question_answer_path(question, answer),
                data: { turbo_method: :delete, 
                        turbo_confirm: 'Are you sure?' }
      |  | 
      = link_to 'Edit', 
                edit_question_answer_path(question, answer), 
                data: { turbo_frame: "answer"}
    |  | 
    - if current_user&.author_of?(question)
      = link_to 'Choose the best answer', best_answer_question_answer_path(answer, question_id: question.id),
        data: {turbo_method: :patch}

app/views/answers/_answers.html.slim
- answers.each do |answer|
  = render 'answers/answer', answer: answer, question: question

app/views/answers/_best_answer.html.slim
h2 Best answer:
= render 'answers/answer', answer: answer, question: question

app/views/answers/_form.html.slim
- frame_id = local_assigns[:frame_id] || "new_answer"

- if answer.errors.present?
   = render 'shared/errors', resource: answer

= form_with model: [question, answer], data: {turbo_frame: frame_id } do |f|
  p
    = f.label :body, answer.persisted? ? 'Your answer' : 'Body'
    = f.text_area :body
  p 
    = f.label :files 
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p 
  div data-controller="link"
    div data-link-target="newLink"

    template data-link-target="template"
      = f.fields_for :links, Link.new, child_index: "NEW_LINK_INDEX" do |l|
        = render "links/form", f: l

    p
        = button_tag "Add link", type: "button", data: { action: "link#add" }
  p = f.submit answer.persisted? ? 'Save' : 'Submit answer'

app/views/answers/create.js.erb
$('.answer-errors').html("<%= j render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.answers').append("<%= j render @answer %>");
  $('.new-answer #new_answer_body').val('');
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.append "answers",
    partial: "answers/answer",
    locals: { answer: @answer, question: @question} %>

<%= turbo_stream.update "new_answer",
    partial: "answers/form",
    locals: { answer: Answer.new, question: @question} %>

app/views/answers/edit.html.slim
turbo-frame id = dom_id(@answer)
  = render 'answers/form', answer: @answer, question: @question, frame_id: dom_id(@answer)

app/views/answers/update.js.erb
$('.answer-errors').html("<%= j render 'shared/errors', resource: @answer %>");

<% if !@answer.errors.present? %>
  $('.answers').html("<%= j render @question.answers %>");
<% end %>